stages:
  - test
  - build

pytest:
  stage: test
  image: ghcr.io/astral-sh/uv:python3.13-bookworm
  script:
    - uv sync
    - uv run pytest --junitxml=pytest-results.xml
  artifacts:
    when: always
    reports:
      junit: pytest-results.xml

typst:
  stage: build
  image:
    name: ghcr.io/typst/typst:latest
    entrypoint: [""]
  script:
    - typst compile docs/book.typ architectural_specs.pdf
  artifacts:
    paths:
      - architectural_specs.pdf
    expire_in: 1 week
