[project]
name = "catst"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "gsec", email = "gui@posteo.net" }
]
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.16.1",
    "isort>=8.0.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pytest>=9.1.1",
    "qutip>=5.3.1",
]

[project.scripts]
catst = "catst:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
